// Code generated by protoc-gen-gogo.
// source: github.com/bketelsen/micro/server/proto/math/math.proto
// DO NOT EDIT!

/*
Package math is a generated protocol buffer package.

It is generated from these files:
	github.com/bketelsen/micro/server/proto/math/math.proto

It has these top-level messages:
	Request
	Response
*/
package math

import proto "github.com/gogo/protobuf/proto"
import math1 "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math1.Inf

type Request struct {
	Num              *int32 `protobuf:"varint,1,req,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type Response struct {
	Num              *int32 `protobuf:"varint,1,req,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func init() {
}
